# Файл: backend/Dockerfile (Финальная рабочая версия)

# 1. Базовый образ
FROM python:3.11-slim

# 2. Переменные окружения
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# 3. Установка рабочей директории
WORKDIR /app

# 4. Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 5. Копирование кода приложения
# Мы находимся в контексте папки 'backend', поэтому копируем всё из текущей папки (.)
# в рабочую директорию контейнера (/app).
COPY . .

# 6. Команда для запуска приложения
# Gunicorn будет слушать порт, который ему передаст Cloud Run
CMD ["gunicorn", "backend.wsgi", "--bind", "0.0.0.0:$PORT"]