# Generated by Django 5.2.6 on 2025-09-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_client_birthday_client_status_tag_client_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата фактического выполнения'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('PEND', 'Ожидает'), ('INP', 'В работе'), ('COMP', 'Выполнено'), ('OVRD', 'Просрочено')], default='PEND', max_length=4, verbose_name='Статус SLA'),
        ),
    ]
